language: cpp

services:
  - rabbitmq

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo apt-get update -qq

install:
 - sudo apt-get -qq install boost1.55 gcc-4.8 g++-4.8
 - sudo apt-get install lua5.1 liblua5.1-dev
 - sudo apt-get install luarocks
 - sudo luarocks install busted

before_script:
  - export CXX="g++-4.8"
  - sudo ./build_rabbitmq

script:
  - export LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH;
  - make -C Build config=release
  - busted test/test_connection.lua
  - busted test/test_channels.lua
  - busted test/test_ack.lua
  - busted test/test_consume.lua
  - busted test/test_exchange.lua
  - busted test/test_get.lua
  - busted test/test_message.lua
  - busted test/test_publish.lua
