language: cpp

services:
  - rabbitmq

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libboost1.55-all-dev
      - liblua5.1-0
      - lua5.1
      - luarocks

before_script:
  - export CXX="g++-5"
  - export AMQP_BROKER="localhost"
  - sudo ./build_rabbitmq
  - luarocks install busted

script:
  - export LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH;
  - make -C Build/linux/gmake config=release64
  - busted test/test_connection.lua
  - busted test/test_channels.lua
  - busted test/test_ack.lua
  - busted test/test_consume.lua
  - busted test/test_exchange.lua
  - busted test/test_get.lua
  - busted test/test_message.lua
  - busted test/test_publish.lua
