language: cpp

services:
  - rabbitmq

before_script:
  - sudo add-apt-repository --yes ppa:apokluda/boost1.53
  - sudo apt-get --yes update
  - sudo apt-get --yes install libboost1.53-all-dev
  - sudo apt-get install lua5.1 liblua5.1-dev
  - sudo apt-get install luarocks
  - sudo luarocks install busted
  - sudo ./build_rabbitmq

script:
  - export LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH;
  - make -C Build config=release
  - busted test/test_connection.lua
  - busted test/test_channels.lua
  - busted test/test_ack.lua
  - busted test/test_consume.lua
  - busted test/test_exchange.lua
  - busted test/test_get.lua
  - busted test/test_message.lua
  - busted test/test_publish.lua